### ISSUE TITLE
SG March/April 2024

### ISSUE THREAD

**Issue by docuracy** [WorldHistoricalGazetteer/whg3#142]
_1 June beta launch is **_hard_** deadline. KG is on a plane 2 June and unavailable 2-6, then 1-day-per-week afterwards; so it is "minimum viable product (MVP)" time_. This is beta, so some things can be deferred.

- [x] Portal page (per requested changes from week of 18 March)
    - [x] Rebuild temporal control to incorporate histogram and provide dragbar functionality
    - [x] Return ecological attributes 
    - [x] Include admin areas
    - [x] elevation (?)
    - [ ] ~~& PeriodO~~ attributes 
    - [x] Compute watershed button (as time permits, if dataset not available)
- [x] Search page
    - [x] Split Region/Country input
    - [ ] ~~Add PeriodO Input~~ needs investigation & not a June 1 priority; no call for it from team
- [x] Home: standardise Search input with Search Page
- [x] Mobile+responsivity for public pages:
    - [x] **Home** (**propose** new layout, now with 3 'big buttons' not 4)
    - [x] Search
    - [x] Place Portal
    - [x] Place detail
- [x] Extend map style to incorporate switchable OSM layers for place-names, roads, waterways, and rail (essential for 10+ zoom levels)
    - [ ] for which maps?
- [x] Investigate:
    - [ ] ~~Best practice API namespaces/URIs~~
    - [ ] ~~Inventory existing external API endpoints, provide developer access to explore them~~
    - [ ] ~~Multilingual CMS (as time permits)~~
    - [ ] ~~OSM place-names as an additional reconciliation dataset?~~

**Comment by kgeographer** [comment]
Refraining from editing the list for the moment, some thoughts:
- apart from the below thought, the list looks good
- nature of any integration of PeriodO data needs team discussion before any coding or experimentation
- the histogram/time control would entail a deep dive into D3 and assuming you haven't dived in to date, cost of getting up to speed would ideally be shared. The D3 learning curve is notoriously steep.
- re: more data...I plan to index geonames and tie that in to reconciliation services; also to build up our TGN holdings...in fact possibly to offer a TGN API as an outreach to Getty. Also looking at "[who's on first](https://www.whosonfirst.org/)." Hadn't thought of OSM places; will investigate closely. From a quick look I *think* it incorporates a ton of geonames and has much we don't want but maybe some we want. I'm lately really inclined to say almost globally, "more is better." Let's keep index/db/backend with me for now.
- the topic of multilinguality is important and deserves some analysis. all wikidata name variants have language/script codes; possibly much of TGN also. surfacing those and making language an analytic dimension would be a real 'feather in our cap' - a post-beta effort I believe

**Comment by kgeographer** [comment]
Place portal changes/adds, legend below
<img width="1080" alt="image" src="https://github.com/WorldHistoricalGazetteer/whg3/assets/1753945/0f8c1465-0ae8-4f04-98a7-aabfa5cdd611">

**Comment by kgeographer** [comment]
Place portal changes...

1. Info "gloss." This is to be auto generated from attributes available in the payload
2. 'add to collection' _was_ for individual attestation, now for the set. several major implications 
3. Sources div needs to be isolated within the column, scrollable, and accordion-foldable
  - order should be latest first (moves things like geonames and TGN to bottom)
4. Add types (sourceLabel) and clarify timespans with simple parens, label as 'Chronology'
5. needs to scroll, if >1, indicate somehow (count in header?)
6. merge slider and histogram somehow; if it turns out to be huge, defer
7. initial zoom should be much further out than 'extent' - extent minus {n}
8. Desired layers
  - Basemaps: a) streetmap default, b) terrain option (NE II, basic light w/hillshade)
  - Physical geography (label uncertain): a) biomes, b) ecoregions, c) lakes and rivers (for terrain only?)
  - One labels checkbox to rule them all
  - Nearby places: filter out the places/markers already shown
