### ISSUE TITLE
VisParameters/Temporal

### ISSUE THREAD

**Issue by docuracy** [WorldHistoricalGazetteer/whg3#159]
SG: Digging into the configuration of temporal controls, I've just realised that `tableFunctions.js` is configured such that only place collections will ever have columns for `start` or `end` properties (or indeed `seq`). Is that how it should be? Do we not need to show such properties for datasets and dataset collections?

KG: About time controls…this hasn’t been thought out fully ... all Place records have at least a start value, but in the great majority of datasets, all of its places have the same year as a publication date of a source — not meaningful in the same way as ‘existed at’ or ‘attested at’ dates, and certainly not like the start/end in the annotations of a place collection. this leads me to think that a configuration option of a dataset should be something like a ‘my dates matter’ toggle - which would lead to a time slider appearing. For a handful of datasets, the time filter widget would be very good if not essential. I don’t think a player option makes sense.
maybe this needs a few more example datasets to work with, which I can do next week.

- [ ] Temporal control options on builder pages (sequencer, player-start-date, player-end-date)
    - [ ] Datasets (no options at present: no change proposed, display should use default of slider for both start- and end-dates)
    - [ ] Dataset Collections (no options at present: no change proposed, display should use default of slider for both start- and end-dates)
    - [ ] Place Collections (all 3 options at present: no change proposed)
- [ ] Temporal control configuration/test
    - [ ] http://localhost:8001/datasets/10/places (_both_ showing)
    - [ ] http://localhost:8001/collections/14/browse_ds  (_both_ showing)
    - [ ] http://localhost:8001/collections/13/browse_pl (date slider only)
    - [ ] http://localhost:8001/collections/11/browse_pl (sequencer only)

**Comment by kgeographer** [comment]
On further reflection...I guess if someone chooses to display a time slider for a dataset or dataset collection, because their dates are meaningful (i.e. related to the place's existence, not the pub date of the source), then start and end columns should be available. So the toggle switch label should reflect that, and 'show slider' should in fact enable start/end columns.

I realize that some time back I thought time only mattered to place collections, and requested that constraint. I was wrong. Hope this isn't too big a hassle; it is fairly critical though I think. My bad as the kids say.

**Comment by docuracy** [comment]
Merged with #177
