### ISSUE TITLE
select for PASS numbers in review and accession

### ISSUE THREAD

**Issue by kgeographer** [WorldHistoricalGazetteer/whg3#185]
The select at the top of the review.html and accession.html pages initially displays the correct PASS, but something in javascript resets it immediately to a blank row, Oddly (?) if a PASS number is chosen then the select behaves normally
<img width="156" alt="image" src="https://github.com/WorldHistoricalGazetteer/whg3/assets/1753945/53f84c70-8b90-455c-b381-5f1799d4de5a">

<img width="161" alt="image" src="https://github.com/WorldHistoricalGazetteer/whg3/assets/1753945/e89f002c-ceea-4e1d-a06f-2f75e404a353">

**Comment by docuracy** [comment]
On initial inspection, I cannot see how this would be preset with the correct option selected - there is no `selected` property on any of the options, and in the JavaScript the code that would set `#select_pass` is commented out:

```
          <select id="select_pass" name="pass" class="custom-select-sm me-2" style="width:auto;">
						{% if count_pass0 > 0 %}
              <option value="pass0">PASS 0 (auto-matched)&nbsp;</option>
            {% endif %}
            {% if count_pass1 > 0 %}
              <option value="pass1">PASS 1&nbsp;</option>
            {% endif %}
            {% if count_pass2 > 0 %}
              <option value="pass2">PASS 2&nbsp;</option>
            {% endif %}
            {% if count_pass3 > 0 %}
              <option value="pass3">PASS 3&nbsp;</option>
            {% endif %}
					</select>
```

```
	// set pass dropdown as next set with any reviewed=False rows
	// $("#select_pass").val(passnum);
```

**Comment by kgeographer** [comment]
<img width="401" alt="image" src="https://github.com/WorldHistoricalGazetteer/whg3/assets/1753945/ddeb603d-5d59-4069-b02b-3edc6529c545">
fixed - sorry, should have closed the issue

**Comment by docuracy** [comment]
@kgeographer : I can't figure out what the _intended_ behaviour is. This is commented out, 

```
	// set pass dropdown as next set with any reviewed=False rows
	// $("#select_pass").val(passnum);
```

presumably because the <option> values in the <select> are of the form "pass0", "pass1" etc, which would explain why you were getting blank selections. The code would need to be:

```
	$("#select_pass").val(`pass${passnum}`);

```

But that won't answer this case if Pass 1 is selected for review:

![Image](https://github.com/WorldHistoricalGazetteer/whg3/assets/42514781/ff5d187a-964a-4e08-88c9-7adbf20a56ae)

... because there won't be an option with value="pass1", and again you would get a blank selection. In that case, am I to understand that you would want "pass2" to be selected rather than "pass 0"?

**Comment by docuracy** [comment]
Uh? I see you've closed this while I was working on it and my last comment got mangled in the process.

**Comment by kgeographer** [comment]
yes, the issue was simply that a pass integer wsas getting passed around and it need concatenation with 'pass' at some point
