### ISSUE TITLE
Nits, bugs & deep thoughts: beta final survey

### ISSUE THREAD

**Issue by kgeographer** [WorldHistoricalGazetteer/whg3#193]
### not all are musts

**for discussion (some will be post 1 June development)**
- [x] anything tagged (sg comments?)
- [x] scaling of orange markers based on some feature density measure

**home page**
- [x] uneven height of left & right columns a bit disconcerting <<shrug?>> (kg)
  - [x] ideas for blank spaces? (sg comments?)
- [x] some red markers don't work on previews, e.g.

**search**
- [x] types appears twice in result card (sg)
- [x] filtering on type and countries could use check all/clear all functionality (or 'only' link per flight sites) (sg)
- [x] typeahead on input has odd results - random and not 'starts with' (image [1] below). (sg comments?)
- [x] is progressive load of categories necessary? they are not dynamic & the display stutters  (sg comments?)
- [x] inoperability of advanced pre-filter checkboxes upon search results is a hanging UX problem  (sg comments?)
- [ ] search result gets child names but not types or fclasses; a refactor of search gets its own issue (kg)
- [x] upon clear, initial blurb should reappear
- [x] result features need buffer

**api**
- [x] the legacy endpoints are sorely deficient
  - [x] returning an index parent returns list of child pids, not useful for anyone without an elaborate crawling script
  - [x] the `fclass` variable doesn't reach fclass values of children
  - [x] fix mixed results, json formatting for existing endpoints
  - [ ] spatial queries are database, not index, FWIW <<shrug>> for now

**review**
- [x] ~the "already" logic in place to allow multiple reviewers on the same dataset (both reconciliation and accessioning) works. not sure whether the new `if (already !=='')` block in review.js will impact that~

**reconciliation**
- [ ] get exact and near-exact name + geometry results into pass0 queue (kg)

**emailing**
- [ ] custom subjects for more messages (kg)
- [ ] apply construct_display_name() for all emailing (kg)

**promotion, etc.**
- [ ] new blog site theme needed (kg)

**general**
- [ ] would be nice to copy coordinates from marker popups in spots

[1] 
![image](https://github.com/WorldHistoricalGazetteer/whg3/assets/1753945/af4f2f6d-778b-4684-b6e7-c459ae71dc4d)

**admin dashboard**
- [x] sort by/filter owner
- [x] scroll below tabs

**Place Collection builder (place_collection_build)**
- [x] add dataset places fails
- [x] remove place fails
 
**user dashboard**
- [x] scroll within boxes

**ds_status**
- [x] temporal default to "no"

**ds_metadata**
- [x] move file info; clean up

**ds_collection_build**
- [x] temporal default to "no"
- [x] initial save redirect to self

**GENERAL**
- [x] remove all references to "builder"
- [x] add collaborator should be username, not email anymore
- [ ] standardize `is_admin` across site

**Comment by docuracy** [comment]
**Home Page Layout**

Rather than add more content to the Home Page and distract from what is already there, my preference would be to refactor the content to two equal-width columns, by adding the current right-column content to the bottom of the left-column and dynamically-adjusting the map height to ensure matching of column-heights.

We would specify a nominal map height for use in narrower viewports where the columns become stacked.

While making those adjustments we should also add back in the footer bar, and then hide it until its content is resolved.

**Comment by docuracy** [comment]
Re: "inoperability of advanced pre-filter checkboxes upon search results is a hanging UX problem (sg comments?)"

The effect of _un-_checking a pre-filter checkbox _could_ be implemented on the results, but the reverse is not true and requires a re-search, which of course is why we now clear the results if those pre-filter checkboxes are changed.

In terms of UX, my preference was to disable the pre-filter checkboxes because having results vanish is worse than having to clear the results manually before re-searching.

**Comment by docuracy** [comment]
Re: "typeahead on input has odd results - random and not 'starts with' (image [1] below). (sg comments?)"

The problem here is that the Elastic index is not configured with nested mapping on the `names` field, and so the search results return an array of all variant toponyms for each hit.

I could fudge it with post-processing for 'exact' and 'starts' searches, but 'fuzzy' would be problematic. I'd really prefer to mess with the Elastic index (or preferably with a `dev` copy) - are you able/willing to let me loose on that? Perhaps on Contract #07?

**Comment by kgeographer** [comment]
> Re: "inoperability of advanced pre-filter checkboxes upon search results is a hanging UX problem (sg comments?)"
> 
> The effect of _un-_checking a pre-filter checkbox _could_ be implemented on the results, but the reverse is not true and requires a re-search, which of course is why we now clear the results if those pre-filter checkboxes are changed.

I had not seen this happen before - it does mitigate the problem.

> 
> In terms of UX, my preference was to disable the pre-filter checkboxes because having results vanish is worse than having to clear the results manually before re-searching.

disabling the pre-filter checkboxes upon return of results was always my first choice. Second choice was to do away with them altogether, as people are accustomed to just making a search/query and THEN managing the result

**Comment by kgeographer** [comment]
> Re: "typeahead on input has odd results - random and not 'starts with' (image [1] below). (sg comments?)"
> 
> The problem here is that the Elastic index is not configured with nested mapping on the `names` field, and so the search results return an array of all variant toponyms for each hit.

It was not a problem until typeahead was enabled ;^) Not sold on the usefulness of it, which is why I disabled it in v2 after initially including it.

> 
> I could fudge it with post-processing for 'exact' and 'starts' searches, but 'fuzzy' would be problematic. I'd really prefer to mess with the Elastic index (or preferably with a `dev` copy) - are you able/willing to let me loose on that? Perhaps on Contract #7?

I think some intensive work with ES and queries to it is in order but not now. Maybe #7?

**Comment by docuracy** [comment]
**Re "It was not a problem until typeahead was enabled":**

I _think_ this is because before you were searching only on the `title` field, and not getting any suggestions for place names that appear only among toponym aliases.

**Comment by docuracy** [comment]
**Re: "would be nice to copy coordinates from marker popups in spots"**

Because the marker popups are (all?) dependent on hover it's not possible to click on them. But there could be a message within the popups to indicate that a right-click (or a shift-click?) will copy the geometry to the user's clipboard. But in what format? A lat, lng pair might be the most useful for Points, but some use cases demand lng, lat instead, and what about multipoint, (multi-)line, and (multi-)polygon geometries? GeoJSON in all cases?

**Comment by kgeographer** [comment]
> **Re "It was not a problem until typeahead was enabled":**
> 
> I _think_ this is because before you were searching only on the `title` field, and not getting any suggestions for place names that appear only among toponym aliases.

Disabled it because it wasn't performant. There was a "suggest" completion field field in the index, populated by all the "toponym" values in all of the PlaceName records of a place. This was the mapping
```
      "suggest" : {
        "type" : "completion",
        "analyzer" : "simple",
        "preserve_separators" : true,
        "preserve_position_increments" : true,
        "max_input_length" : 50,
        "contexts" : [
          {
            "name" : "place_type",
            "type" : "CATEGORY",
            "path" : "types.identifier"
          }
        ]
      },
 ```
Don't recall it returning names that were not a 'startswith' match
