### ISSUE TITLE
Irregular `fclasses`

### ISSUE THREAD

**Issue by docuracy** [WorldHistoricalGazetteer/whg3#244]
A search for "Mariana Trench" finds a place which has feature class "X", which is not handled by either the Place Categories in Advanced Options or Place Types in Filter Results. In fact it breaks Filter Results.

**Comment by kgeographer** [comment]
'X' was meant to handle the fact that for a long time, many records had no fclass value, because they were never required until v3, and if someone used an fclass pre-filter, then records that conceivable were candidates would be omitted. So as I recall (would have to dive in for a look) searches against the index return all otherwise worthy hits with your requested fclasses AND any with 'X" in that array in the index. I backfilled all whg index record fclasses arrays  with an 'X'. 
NB It would not surprise me if there was a better way to handle this, but it worked

**Comment by docuracy** [comment]
OK, I'll fix the Place Types filter to handle it.
