### ISSUE TITLE
search page

### ISSUE THREAD

**Issue by kgeographer** [WorldHistoricalGazetteer/whg3#26]
`search\templates\search\search_new.html`
http://localhost:8001/search/

### major remake: search results w/filters + new search
_NB. modeled on 'typical' library search_ interfaces

#### 5 screen elements

- (1) search input w/advanced options in expanding div 'dropdown'
- (2) result facet filters
- (3) results in scrolling table of result 'cards'
  - click card, some detail in lower right (5); geometry focused in map (4)
  - click link to go to Place Portal
- (4) map shows geometry of all initially
  - click marker, list scrolls to result
- (5) detail preview (?); more detail than card, less than Place Portal

**Comment by kgeographer** [comment]
![Image](https://github.com/WorldHistoricalGazetteer/whg3/assets/1753945/0a3c06d6-8744-41e4-9a4a-c82d58a823e9)

**Comment by kgeographer** [comment]
![Image](https://github.com/WorldHistoricalGazetteer/whg3/assets/1753945/b948391f-f492-44f5-b475-283bf9a61c32)

**Comment by docuracy** [comment]
Things yet to be addressed:

- [ ] I've adjusted the code to save the search term as an additional FeatureCollection property in localStorage: it might be a good idea to save the checkbox states too, so that revisiting will load the same feature set.
- [ ] Clicking on the empty search box triggers a search (should it wait for at least 3 characters, [Enter], and/or a click on the magnifying glass?).
- [ ] Clearing or otherwise editing the contents of the search box does not clear the results.
- [ ] There ought to be a +/- map zoom control.
- [ ] Should there be a temporal control to filter results?
- [ ] There is as yet no portal page (e.g. http://localhost:8001/places/13208854/portal), but I've coded the links.

**Comment by kgeographer** [comment]
1. sounds good
2. also good
3. first though is existing results needn't clear until a new result set arrives
4. sure
5. no need right now; let's revisit later
6. I've been working on the way to navigate to the portal page with all the relevant pids; it is highly likely this work would step on what you've done, there is overlap. I suggest you take this to a wrapped-for-now stage, and issue a PR. I would then have to ensure the links in the result divs return all the detail required for the portal page. So I could do the "on top of" your PR branch, verify it all works, and merge back to staging when it does.

**Comment by docuracy** [comment]
**TODO**

- [ ] Temporal control to filter results
