### ISSUE TITLE
Not a bug but kind of annoying - place collections

### ISSUE THREAD

**Issue by alexstrb** [WorldHistoricalGazetteer/whg3#288]
I am testing out place collections. LOVE the new interface. Especially adding a pic per place. One annoying thing I noticed - whenever I click "save annotation" under the "add and annotate places" page, it kicks me back to the "edit collection" page. Not a huge deal but kind of annoying since I wanted to do all my annotations at once.

**Comment by alexstrb** [comment]
Adding to this - I am trying to add Hollywood to my place collection. We have multiple entries for Hollywood, but they are not in the index so no place portal page. Can we add maybe add something to the place details page that says something like "this place cannot be added to a collection - sorry!" or something. I think it will be confusing for people to be able to see the place but not add it to the collection.

**Comment by docuracy** [comment]
1. Resolved
2. Good point. I've moved the button to a more intuitive location, and replaced it with an apology for unlinked places (which now appear on their own portal page instead of a place detail page).

![Image](https://github.com/user-attachments/assets/06f322f2-78b4-4593-97cd-afd8b3f3d4b1)
![Image](https://github.com/user-attachments/assets/6d29a890-e8c2-4cfc-b62f-e9ee1a401540)
