### ISSUE TITLE
504 Gateway Time-out when uploading dataset

### ISSUE THREAD

**Issue by alexstrb** [WorldHistoricalGazetteer/whg3#318]
Hi - I am trying to upload a dataset. I tried to upload it probably 3 times and each time received error catches which I fixed (mostly having to do with incorrect country codes). I am trying to upload the revised dataset and I keep getting a 504 Gateway time-out message.

**Comment by docuracy** [comment]
Thanks for letting me know, Ali. I had this 504 problem myself a week or so ago, which is why I started Issue #294. I _think_ fixing it is going to entail a couple of days spent rebuilding the validation and ingestion pipeline, but can you tell me how many features/lines are involved, and is it LP-TSV rather than LPF JSON?

**Comment by alexstrb** [comment]
Thanks for your reply! I am trying to upload a .csv file (LP-TSV). There are 3043 rows. Attaching the .csv here. 

[Sound Toll Registers (2) - Sound Toll Registers (2) (4).csv](https://github.com/user-attachments/files/16367277/Sound.Toll.Registers.2.-.Sound.Toll.Registers.2.4.csv)

**Comment by alexstrb** [comment]
Hey Stephen - just checked and despite the error, I seem to have uploaded four datasets (1523, 1524, 1525, 1526). I did check for them when I first was getting the errors and did not see them, so I guess they take a few minutes to reflect in my dashboard. hope I am not making something of nothing!

**Comment by alexstrb** [comment]
(also note to myself really but I will need to mess with the dataset a little more because it has some random countries <i.e. Australia> in it and they should be removed)

**Comment by docuracy** [comment]
Ah, OK - I think what happens is that your browser gets fed up of waiting for a response from the server and drops the connection, but the server carries on processing the dataset regardless. One of the things I want to implement is running the processing as a background task, so that the browser can intermittently check to get a progress report until it either completes or fails. Seems to me like a top-priority job.

**Comment by alexstrb** [comment]
Ok gotcha. And yes seems like a priority too. Thanks for the quick replies!

**Comment by kgeographer** [comment]
Same happening for dataset 1535 (heritage sites). 504 gateway timeout despite loading successfully.
