### ISSUE TITLE
Visualization Options on Place Collection builder

### ISSUE THREAD

**Issue by jesse-obert** [WorldHistoricalGazetteer/whg3#388]
Hello,

There are two issues here:

1. The red question mark doesn't do anything or bring up any pop-up
2. The Trail sort option does not appear to work. In general, it's not clear to me that anything in the Visualization Options is working as intended, but I can't really speak to the sequencer. I honestly don't know what is supposed to happen here.

Thanks,
Jesse

<img width="368" alt="Vis" src="https://github.com/user-attachments/assets/88602bc6-f077-46e5-b168-2e54c2dfa51a">

**Comment by docuracy** [comment]
In the next update I've removed the red question mark, and made all of the popups more prominent.

It wasn't explained that ant-trails cannot be displayed if ANY record is lacking geometry, but otherwise I'm not sure how I might clarify the texts. Any suggestions?

![image](https://github.com/user-attachments/assets/3af815ed-dec2-4338-9660-6ed1bdc11369)
![image](https://github.com/user-attachments/assets/0ac3bde7-a4ab-47a6-8658-b3067158b63e)
![image](https://github.com/user-attachments/assets/cace9da9-cfd6-4d7a-878f-6b42c0565dcc)
![image](https://github.com/user-attachments/assets/e909fb34-c0e1-4601-bec8-e247ec9ca12e)
