### ISSUE TITLE
Navigation Issue from Place Portal Page

### ISSUE THREAD

**Issue by jesse-obert** [WorldHistoricalGazetteer/whg3#389]
Hello,

During Ali's walkthrough, one of the teachers asked about data legitimacy on the Place portal page. She used Petrograd as an example (https://whgazetteer.org/places/12345938/portal/). Ali said they could hover over the names of each dataset to learn more, but they all agreed that was insufficient. Their specific comment was that the pop-up "is useless." Ali showed them how they could learn more about each dataset by navigating to that specific dataset page through Data>Published Datasets.

Can we add a link to the pop-up on the place portal page that connected each dataset to their respective dataset page? So someone on the Petrograd page can go see what the DK Atlas is, for example, in only one click.

Thanks,
Jesse

**Comment by docuracy** [comment]
I've altered the behaviour (in the next update) so that the popup appears on hover (as before), and a click on the link takes the user through to the dataset page. As anyone would expect, I suppose.

**Comment by docuracy** [comment]
... realised that there's a big problem with linking to dataset pages for things like the TGN dataset, which has 1.8 million records, far more than the dataset pages are designed to cope with. In such cases there's really not anything more we can offer than what is on the popup, however useless that might seem.

I'll modify the code so that only published datasets are linked.

**Comment by docuracy** [comment]
A dataset size limit is now configured in `settings.py` (currently 100k records). If its `ds_places` page is called inadvertently a 503 "Service Unavailable" page is delivered.

![image](https://github.com/user-attachments/assets/30d21f1c-50e6-4289-84b0-fddd2e24458e)
